#:schema node_modules/wrangler/config-schema.json
name = "sublink-pages1"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "4c6aec8ee6004d109382c492a8801d58" }
]

[assets]
directory = "./public"
